# Generated by Django 5.1.6 on 2025-02-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_attendance', '0002_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sports_attendance/student_photos/'),
        ),
    ]
